/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyShopGame;

import QuanLyShopGame.NguoiDung.NguoiDung;
import QuanLyShopGame.Panel.pGiftCode;
import QuanLyShopGame.Panel.pLichSuGD;
import QuanLyShopGame.Panel.pMuaNhieu;
import QuanLyShopGame.Panel.pNapTien;
import QuanLyShopGame.Panel.pNew;
import QuanLyShopGame.Panel.pThongTinNguoiDung;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class frmCuaSoChinh extends javax.swing.JFrame {

    private static boolean trangThaiDangNhap = false;

    public static boolean isTrangThaiDangNhap() {
        return trangThaiDangNhap;
    }

    public static void setTrangThaiDangNhap(boolean trangThaiDangNhap) {
        frmCuaSoChinh.trangThaiDangNhap = trangThaiDangNhap;
    }
    
    public static NguoiDung user = null;

    public static NguoiDung getUser() {
        return user;
    }

    public static void setUser(NguoiDung user) {
        frmCuaSoChinh.user = user;
    }
    
    SanPhamDao spDao = new SanPhamImpl();
    public static SanPham objSP;
    
    /**
     * Creates new form frmCuaSoChinh
     */
    public frmCuaSoChinh() {
        initComponents();
        this.setTitle("Main");
        final boolean showTabsHeader = false;
        tpMain.setUI(new javax.swing.plaf.metal.MetalTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int horizRunCount, int maxTabHeight) {
                if (showTabsHeader) {
                    return super.calculateTabAreaHeight(tabPlacement, horizRunCount, maxTabHeight);
                } else {
                    return 0;
                }
            }

            protected void paintTabArea(Graphics g, int tabPlacement, int selectedIndex) {
            }
        });
        tpTrangChu.setUI(new javax.swing.plaf.metal.MetalTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int horizRunCount, int maxTabHeight) {
                if (showTabsHeader) {
                    return super.calculateTabAreaHeight(tabPlacement, horizRunCount, maxTabHeight);
                } else {
                    return 0;
                }
            }

            protected void paintTabArea(Graphics g, int tabPlacement, int selectedIndex) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        lblGioHang = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTrangChu = new javax.swing.JLabel();
        tpMain = new javax.swing.JTabbedPane();
        pMain = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tpTrangChu = new javax.swing.JTabbedPane();
        pMuaNhieu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblAnh1 = new javax.swing.JLabel();
        lblTen1 = new javax.swing.JLabel();
        lblGia1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblAnh2 = new javax.swing.JLabel();
        lblTen2 = new javax.swing.JLabel();
        lblGia2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblAnh3 = new javax.swing.JLabel();
        lblTen3 = new javax.swing.JLabel();
        lblGia3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblAnh4 = new javax.swing.JLabel();
        lblTen4 = new javax.swing.JLabel();
        lblGia4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMIThongTin = new javax.swing.JMenuItem();
        jMINapTien = new javax.swing.JMenuItem();
        jMILichSu = new javax.swing.JMenuItem();
        jMILogout = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMITatCa = new javax.swing.JMenuItem();
        jMIGame = new javax.swing.JMenuItem();
        jMIThietBi = new javax.swing.JMenuItem();
        jMIItem = new javax.swing.JMenuItem();
        jMITheNap = new javax.swing.JMenuItem();
        iMenuGiftCode = new javax.swing.JMenu();
        iMITuan = new javax.swing.JMenuItem();
        jMIHe = new javax.swing.JMenuItem();
        jMIDong = new javax.swing.JMenuItem();
        jMenuHuongDan = new javax.swing.JMenu();
        jMenuHoTro = new javax.swing.JMenu();

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lblGioHang.setIcon(new javax.swing.ImageIcon("E:\\Java\\ImageIcon\\mini_icon_set\\Mini Icon Set\\PNG\\16x16\\14.png")); // NOI18N
        lblGioHang.setText("Giỏ hàng");
        lblGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGioHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGioHangMouseEntered(evt);
            }
        });

        lblTaiKhoan.setIcon(new javax.swing.ImageIcon("E:\\Java\\ImageIcon\\mini_icon_set\\Mini Icon Set\\PNG\\16x16\\32.png")); // NOI18N
        lblTaiKhoan.setText("Tài khoản");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Trang chủ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTaiKhoan)
                .addGap(64, 64, 64)
                .addComponent(lblGioHang)
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGioHang)
                    .addComponent(lblTaiKhoan)
                    .addComponent(jLabel1))
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(lblTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tpMain.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setText("Danh mục");

        jButton1.setText("Mua nhiều");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnNew.setText("Hàng mới về");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        jButton3.setText("Đang giảm giá");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTen1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTen1.setText("jLabel3");
        lblTen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTen1MouseClicked(evt);
            }
        });

        lblGia1.setText("jLabel4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblAnh1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTen1)
                    .addComponent(lblGia1))
                .addGap(0, 69, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnh1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(lblTen1)
                .addGap(18, 18, 18)
                .addComponent(lblGia1)
                .addGap(29, 29, 29))
        );

        lblTen2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTen2.setText("jLabel11");
        lblTen2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTen2MouseClicked(evt);
            }
        });

        lblGia2.setText("jLabel12");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(lblAnh2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTen2)
                    .addComponent(lblGia2))
                .addGap(0, 59, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnh2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTen2)
                .addGap(18, 18, 18)
                .addComponent(lblGia2)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        lblTen3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTen3.setText("jLabel6");
        lblTen3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTen3MouseClicked(evt);
            }
        });

        lblGia3.setText("jLabel7");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(lblAnh3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTen3)
                    .addComponent(lblGia3))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnh3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTen3)
                .addGap(18, 18, 18)
                .addComponent(lblGia3)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        lblTen4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTen4.setText("jLabel13");
        lblTen4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTen4MouseClicked(evt);
            }
        });

        lblGia4.setText("jLabel14");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(lblAnh4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTen4)
                    .addComponent(lblGia4))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnh4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTen4)
                .addGap(18, 18, 18)
                .addComponent(lblGia4)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pMuaNhieuLayout = new javax.swing.GroupLayout(pMuaNhieu);
        pMuaNhieu.setLayout(pMuaNhieuLayout);
        pMuaNhieuLayout.setHorizontalGroup(
            pMuaNhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMuaNhieuLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pMuaNhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(pMuaNhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        pMuaNhieuLayout.setVerticalGroup(
            pMuaNhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMuaNhieuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pMuaNhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(pMuaNhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        tpTrangChu.addTab("tab1", pMuaNhieu);

        javax.swing.GroupLayout pMainLayout = new javax.swing.GroupLayout(pMain);
        pMain.setLayout(pMainLayout);
        pMainLayout.setHorizontalGroup(
            pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMainLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tpTrangChu))
        );
        pMainLayout.setVerticalGroup(
            pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tpTrangChu)
        );

        tpMain.addTab("tab1", pMain);

        jMenu6.setIcon(new javax.swing.ImageIcon("E:\\Java\\HocVien\\macanhthanh\\Project_QuanLyShopGame\\src\\main\\java\\image\\image\\images\\Group 3.png")); // NOI18N
        jMenu6.setText("Tài khoản");

        jMIThongTin.setIcon(new javax.swing.ImageIcon("E:\\Java\\ImageIcon\\mini_icon_set\\Mini Icon Set\\PNG\\16x16\\32.png")); // NOI18N
        jMIThongTin.setText("Thông tin tài khoản");
        jMIThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIThongTinActionPerformed(evt);
            }
        });
        jMenu6.add(jMIThongTin);

        jMINapTien.setIcon(new javax.swing.ImageIcon("E:\\Java\\ImageIcon\\mini_icon_set\\Mini Icon Set\\PNG\\16x16\\38.png")); // NOI18N
        jMINapTien.setText("Nạp tiền");
        jMINapTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMINapTienActionPerformed(evt);
            }
        });
        jMenu6.add(jMINapTien);

        jMILichSu.setIcon(new javax.swing.ImageIcon("E:\\Java\\ImageIcon\\mini_icon_set\\Mini Icon Set\\PNG\\16x16\\9.png")); // NOI18N
        jMILichSu.setText("Lịch sử giao dịch");
        jMILichSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMILichSuActionPerformed(evt);
            }
        });
        jMenu6.add(jMILichSu);

        jMILogout.setIcon(new javax.swing.ImageIcon("E:\\Java\\HocVien\\macanhthanh\\Project_QuanLyShopGame\\src\\main\\java\\image\\image\\images\\logout.png")); // NOI18N
        jMILogout.setText("Đăng xuất");
        jMILogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMILogoutActionPerformed(evt);
            }
        });
        jMenu6.add(jMILogout);

        jMenuBar1.add(jMenu6);

        jMenu1.setIcon(new javax.swing.ImageIcon("E:\\Java\\HocVien\\macanhthanh\\Project_QuanLyShopGame\\src\\main\\java\\image\\image\\images\\select_all_16x16.gif")); // NOI18N
        jMenu1.setText("Danh sách");

        jMITatCa.setIcon(new javax.swing.ImageIcon("E:\\Java\\ImageIcon\\mini_icon_set\\Mini Icon Set\\PNG\\16x16\\39.png")); // NOI18N
        jMITatCa.setText("Tất cả");
        jMITatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMITatCaActionPerformed(evt);
            }
        });
        jMenu1.add(jMITatCa);

        jMIGame.setText("Game");
        jMIGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGameActionPerformed(evt);
            }
        });
        jMenu1.add(jMIGame);

        jMIThietBi.setText("Thiết bị chơi game");
        jMIThietBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIThietBiActionPerformed(evt);
            }
        });
        jMenu1.add(jMIThietBi);

        jMIItem.setText("Vật phẩm trong game");
        jMIItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIItemActionPerformed(evt);
            }
        });
        jMenu1.add(jMIItem);

        jMITheNap.setText("Thẻ nạp");
        jMITheNap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMITheNapActionPerformed(evt);
            }
        });
        jMenu1.add(jMITheNap);

        jMenuBar1.add(jMenu1);

        iMenuGiftCode.setIcon(new javax.swing.ImageIcon("E:\\Java\\ImageIcon\\mini_icon_set\\Mini Icon Set\\PNG\\16x16\\34.png")); // NOI18N
        iMenuGiftCode.setText("Gift Code");
        iMenuGiftCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iMenuGiftCodeActionPerformed(evt);
            }
        });

        iMITuan.setText("Weekend Sale");
        iMITuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iMITuanActionPerformed(evt);
            }
        });
        iMenuGiftCode.add(iMITuan);

        jMIHe.setText("Summer Sale");
        iMenuGiftCode.add(jMIHe);

        jMIDong.setText("Winter Sale");
        iMenuGiftCode.add(jMIDong);

        jMenuBar1.add(iMenuGiftCode);

        jMenuHuongDan.setIcon(new javax.swing.ImageIcon("E:\\Java\\ImageIcon\\mini_icon_set\\Mini Icon Set\\PNG\\16x16\\16.png")); // NOI18N
        jMenuHuongDan.setText("Hướng dẫn mua hàng");
        jMenuBar1.add(jMenuHuongDan);

        jMenuHoTro.setIcon(new javax.swing.ImageIcon("E:\\Java\\HocVien\\macanhthanh\\Project_QuanLyShopGame\\src\\main\\java\\image\\image\\images\\Help-16x16.png")); // NOI18N
        jMenuHoTro.setText("Hỗ trợ");
        jMenuHoTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHoTroMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuHoTro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tpMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tpMain, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGioHangMouseClicked
        // TODO add your handling code here:
        frmGioHang gioHang = new frmGioHang();
        gioHang.setVisible(true);
        frmGioHang.setUser(user);
    }//GEN-LAST:event_lblGioHangMouseClicked

    private void jMITatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMITatCaActionPerformed
        // TODO add your handling code here:
        frmDanhSachSanPham frmDS = new frmDanhSachSanPham();
        frmDS.setVisible(true);
        
    }//GEN-LAST:event_jMITatCaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon(new ImageIcon("E:\\Java\\HocVien\\macanhthanh\\Project_QuanLyShopGame\\src\\main\\java\\image\\image\\Main_Page_icon_Treasures.png").getImage()
                        .getScaledInstance(lblTrangChu.getWidth(), lblTrangChu.getHeight(), Image.SCALE_SMOOTH));
        lblTrangChu.setIcon(img);
        if(trangThaiDangNhap)
        {
            lblTaiKhoan.setText("Chào mừng " + user.getUserName() +"("+ user.getTaiKhoan()+"VND)");
        }
        
        List<SanPham> lstTop4 = spDao.dstop4LuotMua();
        lblTen1.setText(lstTop4.get(0).getTenSP());
        lblGia1.setText(lstTop4.get(0).getGia()+" VND");
        ImageIcon img1 = new ImageIcon(new ImageIcon(lstTop4.get(0).getImg()).getImage()
                        .getScaledInstance(lblAnh1.getWidth(), lblAnh1.getHeight(), Image.SCALE_SMOOTH));
        lblAnh1.setIcon(img1);
        
        lblTen2.setText(lstTop4.get(1).getTenSP());
        lblGia2.setText(lstTop4.get(1).getGia()+" VND");
        ImageIcon img2 = new ImageIcon(new ImageIcon(lstTop4.get(1).getImg()).getImage()
                        .getScaledInstance(lblAnh2.getWidth(), lblAnh2.getHeight(), Image.SCALE_SMOOTH));
        lblAnh2.setIcon(img2);
        
        lblTen3.setText(lstTop4.get(2).getTenSP());
        lblGia3.setText(lstTop4.get(2).getGia()+" VND");
        ImageIcon img3 = new ImageIcon(new ImageIcon(lstTop4.get(2).getImg()).getImage()
                        .getScaledInstance(lblAnh3.getWidth(), lblAnh3.getHeight(), Image.SCALE_SMOOTH));
        lblAnh3.setIcon(img3);
        
        lblTen4.setText(lstTop4.get(3).getTenSP());
        lblGia4.setText(lstTop4.get(3).getGia()+" VND");
        ImageIcon img4 = new ImageIcon(new ImageIcon(lstTop4.get(3).getImg()).getImage()
                        .getScaledInstance(lblAnh4.getWidth(), lblAnh4.getHeight(), Image.SCALE_SMOOTH));
        lblAnh4.setIcon(img4);
    }//GEN-LAST:event_formWindowOpened

    private void jMIGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGameActionPerformed
        // TODO add your handling code here:
        frmDanhSachSanPham dsGame = new frmDanhSachSanPham();
        dsGame.setVisible(true);
        frmDanhSachSanPham.hienThiDanhSachTimKiem("2");
    }//GEN-LAST:event_jMIGameActionPerformed

    private void jMIThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIThongTinActionPerformed
        // TODO add your handling code here:
        pThongTinNguoiDung.setUser(user);
        pThongTinNguoiDung thongTin = new pThongTinNguoiDung();
        tpMain.removeAll();
        tpMain.add(thongTin);
    }//GEN-LAST:event_jMIThongTinActionPerformed

    private void jMIThietBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIThietBiActionPerformed
        // TODO add your handling code here:
        frmDanhSachSanPham dsThietBi = new frmDanhSachSanPham();
        dsThietBi.setVisible(true);
        frmDanhSachSanPham.hienThiDanhSachTimKiem("3");
    }//GEN-LAST:event_jMIThietBiActionPerformed

    private void jMITheNapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMITheNapActionPerformed
        // TODO add your handling code here:
        frmDanhSachSanPham dsTheNap = new frmDanhSachSanPham();
        dsTheNap.setVisible(true);
        frmDanhSachSanPham.hienThiDanhSachTimKiem("1");
    }//GEN-LAST:event_jMITheNapActionPerformed

    private void jMIItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIItemActionPerformed
        // TODO add your handling code here:
        frmDanhSachSanPham iTem = new frmDanhSachSanPham();
        iTem.setVisible(true);
        frmDanhSachSanPham.hienThiDanhSachTimKiem("4");
    }//GEN-LAST:event_jMIItemActionPerformed

    private void jMINapTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMINapTienActionPerformed
        // TODO add your handling code here:
        pNapTien napTien = new pNapTien();
        tpMain.removeAll();
        tpMain.add(napTien);
        
    }//GEN-LAST:event_jMINapTienActionPerformed

    private void iMenuGiftCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iMenuGiftCodeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_iMenuGiftCodeActionPerformed

    private void iMITuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iMITuanActionPerformed
        // TODO add your handling code here:
        pGiftCode gc = new pGiftCode();
        tpMain.removeAll();
        tpMain.add(gc);
    }//GEN-LAST:event_iMITuanActionPerformed

    private void jMILogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMILogoutActionPerformed
        // TODO add your handling code here:
        frmCuaSoChinh.setTrangThaiDangNhap(false);
        frmCuaSoChinh.setUser(null);
        this.setVisible(false);
        frmDangNhap frmLogin = new frmDangNhap();
        frmLogin.setVisible(true);
    }//GEN-LAST:event_jMILogoutActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        tpTrangChu.removeAll();
        pNew hangMoi = new pNew();
        tpTrangChu.add(hangMoi);
    }//GEN-LAST:event_btnNewActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tpTrangChu.removeAll();
        pMuaNhieu muaNhieu = new pMuaNhieu();
        tpTrangChu.add(muaNhieu);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblGioHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGioHangMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblGioHangMouseEntered

    private void lblTen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTen1MouseClicked
        // TODO add your handling code here:
        String tenSp = lblTen1.getText();
        objSP = spDao.chiTietSP(tenSp);
        hienThiChiTiet();
    }//GEN-LAST:event_lblTen1MouseClicked

    private void lblTen2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTen2MouseClicked
        // TODO add your handling code here:
        String tenSp = lblTen2.getText();
        objSP = spDao.chiTietSP(tenSp);
        hienThiChiTiet();
    }//GEN-LAST:event_lblTen2MouseClicked

    private void lblTen4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTen4MouseClicked
        // TODO add your handling code here:
        String tenSp = lblTen4.getText();
        objSP = spDao.chiTietSP(tenSp);
        hienThiChiTiet();
    }//GEN-LAST:event_lblTen4MouseClicked

    private void lblTen3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTen3MouseClicked
        // TODO add your handling code here:
        String tenSp = lblTen3.getText();
        objSP = spDao.chiTietSP(tenSp);
        hienThiChiTiet();
    }//GEN-LAST:event_lblTen3MouseClicked

    private void jMenuHoTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHoTroMouseClicked
        // TODO add your handling code here:
        frmHoTro ht = new frmHoTro();
        ht.setVisible(true);
    }//GEN-LAST:event_jMenuHoTroMouseClicked

    private void jMILichSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMILichSuActionPerformed
        // TODO add your handling code here:
        pLichSuGD.setUser(user);
        pLichSuGD ls = new pLichSuGD();
        tpMain.removeAll();
        tpMain.add(ls);
    }//GEN-LAST:event_jMILichSuActionPerformed

    public static void hienThiChiTiet()
    {
        frmChiTietSP chiTiet = new frmChiTietSP();
        frmChiTietSP.setSp(objSP);
        frmChiTietSP.setUser(user);
        chiTiet.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCuaSoChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCuaSoChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JMenuItem iMITuan;
    private javax.swing.JMenu iMenuGiftCode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMIDong;
    private javax.swing.JMenuItem jMIGame;
    private javax.swing.JMenuItem jMIHe;
    private javax.swing.JMenuItem jMIItem;
    private javax.swing.JMenuItem jMILichSu;
    private javax.swing.JMenuItem jMILogout;
    private javax.swing.JMenuItem jMINapTien;
    private javax.swing.JMenuItem jMITatCa;
    private javax.swing.JMenuItem jMITheNap;
    private javax.swing.JMenuItem jMIThietBi;
    private javax.swing.JMenuItem jMIThongTin;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHoTro;
    private javax.swing.JMenu jMenuHuongDan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblAnh1;
    private javax.swing.JLabel lblAnh2;
    private javax.swing.JLabel lblAnh3;
    private javax.swing.JLabel lblAnh4;
    private javax.swing.JLabel lblGia1;
    private javax.swing.JLabel lblGia2;
    private javax.swing.JLabel lblGia3;
    private javax.swing.JLabel lblGia4;
    private javax.swing.JLabel lblGioHang;
    public static javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblTen1;
    private javax.swing.JLabel lblTen2;
    private javax.swing.JLabel lblTen3;
    private javax.swing.JLabel lblTen4;
    private javax.swing.JLabel lblTrangChu;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel pMuaNhieu;
    private javax.swing.JTabbedPane tpMain;
    private javax.swing.JTabbedPane tpTrangChu;
    // End of variables declaration//GEN-END:variables
}
