/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyShopGame;

import QuanLyShopGame.HoaDonBan.HoaDonBan;
import QuanLyShopGame.HoaDonBan.HoaDonBanCT;
import QuanLyShopGame.HoaDonBan.HoaDonBanCTDao;
import QuanLyShopGame.HoaDonBan.HoaDonBanCTImpl;
import QuanLyShopGame.HoaDonBan.HoaDonBanDao;
import QuanLyShopGame.HoaDonBan.HoaDonBanImpl;
import QuanLyShopGame.NguoiDung.NguoiDung;
import QuanLyShopGame.NguoiDung.NguoiDungDao;
import QuanLyShopGame.NguoiDung.NguoiDungImpl;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import static org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric;

/**
 *
 * @author Admin
 */
public class pVi extends javax.swing.JPanel {

    private static NguoiDung user = null;

    public static NguoiDung getUser() {
        return user;
    }

    public static void setUser(NguoiDung user) {
        pVi.user = user;
    }
    NguoiDungDao ndDao = new NguoiDungImpl();
    GioHangDao ghDao = new GioHangImpl();
    
    float tongHD = ghDao.tongHoaDon(user.getMaKH());
    /**
     * Creates new form pVi
     */
    public pVi() {
        initComponents();
        hienThiThongTin();
//        lblTaiKhoan.setText(user.getTaiKhoan()+"");
//        GioHangDao ghDao = new GioHangImpl();
//        
//        lblTong.setText(ghDao.tongHoaDon()+"");
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labela = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        labelb = new javax.swing.JLabel();
        lblTong = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSoDu = new javax.swing.JLabel();
        btnHuy = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();
        lblThongBao = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(363, 200));

        labela.setText("Tổng đơn hàng :");

        lblTaiKhoan.setText(" ");

        labelb.setText("Tài khoản của bạn :");

        lblTong.setText("    ");

        jLabel2.setText("Khuyến mãi :");

        jLabel3.setText("Số dư :");

        jLabel4.setText("----------------------------------------------------------");

        lblSoDu.setText("     ");

        btnHuy.setText("Huỷ");

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        lblThongBao.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblThongBao.setForeground(new java.awt.Color(255, 0, 0));
        lblThongBao.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXacNhan)
                .addGap(18, 18, 18)
                .addComponent(btnHuy)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(98, 98, 98)
                                .addComponent(lblSoDu, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labela)
                                    .addComponent(labelb))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTong, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaiKhoan)
                    .addComponent(labelb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTong)
                    .addComponent(labela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblSoDu))
                .addGap(18, 18, 18)
                .addComponent(lblThongBao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy)
                    .addComponent(btnXacNhan))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        lblTaiKhoan.setText(user.getTaiKhoan() + "");
        lblTong.setText(tongHD + "");
        float taiKhoan =0,tongDon =0,soDu = 0;
        taiKhoan = Float.parseFloat(lblTaiKhoan.getText());
        tongDon = Float.parseFloat(lblTong.getText());
        if(taiKhoan>tongDon){
            soDu = taiKhoan - tongDon;
            lblThongBao.setText("Thanh toán thành công");
            vietHoaDon();
            
            boolean gioHang = ghDao.xoaTatCa(""+user.getMaKH());
            frmGioHang.hienThiDanhSach();
            
        }else{
            lblThongBao.setText("Tài khoản không đủ, vui lòng nạp thêm");
            soDu = taiKhoan;
            
        }
        
        lblSoDu.setText(soDu+"");
        user = ndDao.layChiTiet(user.getMaKH());
        user.setTaiKhoan(soDu);
        
        boolean kq = ndDao.sua(user);
        frmCuaSoChinh.lblTaiKhoan.setText("Chào mừng " + user.getUserName() +"("+ user.getTaiKhoan()+"VND)");
    }//GEN-LAST:event_btnXacNhanActionPerformed

    public void hienThiThongTin()
    {
        lblTaiKhoan.setText(user.getTaiKhoan()+"");
        
        lblTong.setText(ghDao.tongHoaDon(user.getMaKH())+"");
        
    }
    
    public void vietHoaDon(){
        //Viết hoá đơn bán
        HoaDonBanDao hdDao = new HoaDonBanImpl();
        HoaDonBan objHD = new HoaDonBan();
        String maHoaDon = randomAlphanumeric(6);
        objHD.setMaHD(maHoaDon);
        objHD.setTenHD(user.getTenKH()+ " mua hang");
        Date ngay = new Date();
        objHD.setNgayBan(""+ngay);
        objHD.setTongHD(tongHD);
        objHD.setMaKH(user.getMaKH());
        boolean vietHD = hdDao.themMoi(objHD);
        
        //Viết hoá đơn bán chi tiết
        HoaDonBanCTDao ctDao = new HoaDonBanCTImpl();
        HoaDonBanCT objCT = new HoaDonBanCT();
        objCT.setMaHD(objHD.getMaHD());
        List<GioHang> lstGioHang = ghDao.timKiemGioHang(user.getMaKH());
        for(GioHang gh: lstGioHang){
            objCT.setMaSP(gh.getMaSP());
            objCT.setSoLuong(gh.getSoLuong());
            objCT.setGiaBan(gh.getGia());
            
            boolean vietCT = ctDao.themMoi(objCT);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labela;
    private javax.swing.JLabel labelb;
    private static javax.swing.JLabel lblSoDu;
    private static javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblThongBao;
    private static javax.swing.JLabel lblTong;
    // End of variables declaration//GEN-END:variables
}
